export const MOCK_TRACKS = [
  {
    id: 1,
    sectionCode: 'SEC-NDLS-GZB-LINE1',
    startStation: 'NDLS',
    endStation: 'GZB',
  },
  {
    id: 2,
    sectionCode: 'SEC-GZB-NDLS-LINE2',
    startStation: 'GZB',
    endStation: 'NDLS',
  },
  {
    id: 3,
    sectionCode: 'SEC-NDLS-GZB-LINE3',
    startStation: 'NDLS',
    endStation: 'GZB',
  },
  {
    id: 4,
    sectionCode: 'SEC-NDLS-GZB-LINE4',
    startStation: 'NDLS',
    endStation: 'GZB',
  },
  {
    id: 5,
    sectionCode: 'SEC-DLI-SBB-YAMUNA-UP',
    startStation: 'DLI',
    endStation: 'SBB',
  },
];

export const MOCK_ASSETS = [
  {
    id: 1,
    name: 'Historic Yamuna Bridge BR-01 Steel Girder (KM 4.2 Loha Pul)',
    type: 'BRIDGE',
    department: 'ENGINEERING',
    trackId: 5,
    healthScore: 68,
    lastServiced: '10 May 2026',
  },
  {
    id: 3,
    name: 'Heavy Duty Continuous Welded Rail CWR KM 14-17 (Line 2 Down)',
    type: 'TRACK',
    department: 'ENGINEERING',
    trackId: 2,
    healthScore: 62,
    lastServiced: '15 Jun 2026',
  },
  {
    id: 6,
    name: 'Multi-Aspect Color Light Home Signal S-14 (Sahibabad Entry)',
    type: 'SIGNALING',
    department: 'SIGNAL_TELECOM',
    trackId: 2,
    healthScore: 56,
    lastServiced: '25 May 2026',
  },
  {
    id: 8,
    name: 'Point Machine PM-102 (Ghaziabad Central Crossover Motor)',
    type: 'POINT_MACHINE',
    department: 'SIGNAL_TELECOM',
    trackId: 2,
    healthScore: 59,
    lastServiced: '05 Jun 2026',
  },
  {
    id: 13,
    name: '25kV AC Catenary Contact Wire (SBB - GZB Line 2 KM 12-16)',
    type: 'OHE',
    department: 'ELECTRICAL',
    trackId: 2,
    healthScore: 61,
    lastServiced: '01 Jun 2026',
  },
  {
    id: 10,
    name: 'Solid State Electronic Interlocking EI-GZB (Central Cabin)',
    type: 'SIGNALING',
    department: 'SIGNAL_TELECOM',
    trackId: 1,
    healthScore: 95,
    lastServiced: '10 Aug 2026',
  },
  {
    id: 14,
    name: '25kV AC Traction Substation Feeder Circuit Breaker CB-09',
    type: 'SUBSTATION',
    department: 'ELECTRICAL',
    trackId: 1,
    healthScore: 78,
    lastServiced: '22 Jul 2026',
  },
];

export const MOCK_SCHEDULES = [
  {
    id: 1,
    scheduleId: 'schedule-22436',
    trackId: 1,
    trackSectionCode: 'SEC-NDLS-GZB-LINE1',
    trainNumber: '22436',
    trainName: 'Vande Bharat Express (New Delhi - Varanasi)',
    trainType: 'VANDE_BHARAT',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T06:00:00',
    exitTime: '2026-09-08T06:35:00',
    status: 'ON_TIME',
  },
  {
    id: 2,
    scheduleId: 'schedule-12004',
    trackId: 1,
    trackSectionCode: 'SEC-NDLS-GZB-LINE1',
    trainNumber: '12004',
    trainName: 'Lucknow Swarna Shatabdi Express',
    trainType: 'SHATABDI',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T06:10:00',
    exitTime: '2026-09-08T06:45:00',
    status: 'ON_TIME',
  },
  {
    id: 6,
    scheduleId: 'schedule-12401',
    trackId: 2,
    trackSectionCode: 'SEC-GZB-NDLS-LINE2',
    trainNumber: '12401',
    trainName: 'Islampur - New Delhi Magadh Express',
    trainType: 'EXPRESS',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T14:10:00',
    exitTime: '2026-09-08T14:45:00',
    status: 'ON_TIME',
  },
  {
    id: 7,
    scheduleId: 'schedule-12015',
    trackId: 2,
    trackSectionCode: 'SEC-GZB-NDLS-LINE2',
    trainNumber: '12015',
    trainName: 'New Delhi - Daurai (Ajmer) Shatabdi Express',
    trainType: 'SHATABDI',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T16:15:00',
    exitTime: '2026-09-08T16:50:00',
    status: 'ON_TIME',
  },
  {
    id: 8,
    scheduleId: 'schedule-12424',
    trackId: 1,
    trackSectionCode: 'SEC-NDLS-GZB-LINE1',
    trainNumber: '12424',
    trainName: 'New Delhi - Dibrugarh Rajdhani Express',
    trainType: 'RAJDHANI',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T16:20:00',
    exitTime: '2026-09-08T16:55:00',
    status: 'ON_TIME',
  },
  {
    id: 3,
    scheduleId: 'schedule-64424',
    trackId: 4,
    trackSectionCode: 'SEC-NDLS-GZB-LINE4',
    trainNumber: '64424',
    trainName: 'Ghaziabad - New Delhi Peak Office Commuter EMU',
    trainType: 'SUBURBAN',
    trainPriority: 'HIGH',
    entryTime: '2026-09-08T08:15:00',
    exitTime: '2026-09-08T09:10:00',
    status: 'ON_TIME',
  },
  {
    id: 5,
    scheduleId: 'schedule-CONCOR-7012',
    trackId: 3,
    trackSectionCode: 'SEC-NDLS-GZB-LINE3',
    trainNumber: 'CONCOR-7012',
    trainName: 'Tughlakabad - Dadri Freight Container Express',
    trainType: 'FREIGHT',
    trainPriority: 'LOW',
    entryTime: '2026-09-08T13:00:00',
    exitTime: '2026-09-08T14:30:00',
    status: 'ON_TIME',
  },
  {
    id: 10,
    scheduleId: 'schedule-14042',
    trackId: 5,
    trackSectionCode: 'SEC-DLI-SBB-YAMUNA-UP',
    trainNumber: '14042',
    trainName: 'Dehradun - Delhi Sarai Rohilla Mussoorie Express',
    trainType: 'EXPRESS',
    trainPriority: 'MEDIUM',
    entryTime: '2026-09-08T07:20:00',
    exitTime: '2026-09-08T08:05:00',
    status: 'ON_TIME',
  },
];

export const MOCK_BLOCKS = [
  {
    id: 1,
    title: 'Heavy Track Tamping & Ballast Regulation KM 14-17',
    trackId: 2,
    trackSectionCode: 'SEC-GZB-NDLS-LINE2',
    startStation: 'GZB',
    endStation: 'NDLS',
    department: 'ENGINEERING',
    assetId: 3,
    assetName: 'Heavy Duty Continuous Welded Rail CWR KM 14-17 (Line 2 Down)',
    scheduledDate: '2026-09-08',
    requestedStartTime: '2026-09-08T14:00:00',
    requestedEndTime: '2026-09-08T17:00:00',
    allocatedStartTime: null,
    allocatedEndTime: null,
    purpose: 'Routine post-monsoon track stabilization',
    status: 'CONFLICT',
    priority: 'HIGH',
    hasConflict: true,
    conflictRemarks: 'Clashes with Magadh 12401 & Shatabdi 12015',
    conflicts: [
      {
        trainNumber: '12401',
        trainName: 'Islampur - New Delhi Magadh Express',
        trainType: 'EXPRESS',
        overlapDurationMinutes: 35,
        severity: 'CRITICAL',
      },
      {
        trainNumber: '12015',
        trainName: 'New Delhi - Daurai (Ajmer) Shatabdi Express',
        trainType: 'SHATABDI',
        overlapDurationMinutes: 35,
        severity: 'CRITICAL',
      },
    ],
    recommendedSlots: [
      {
        proposedStartTime: '2026-09-08T22:00:00',
        proposedEndTime: '2026-09-09T01:00:00',
        disruptionCostScore: 0.0,
        conflictingTrainsCount: 0,
        feasibilityReason: 'Optimal Night Lull Window (01:00 AM - 04:30 AM). Zero passenger and freight disruption.',
        isNightLullWindow: true,
      },
      {
        proposedStartTime: '2026-09-09T01:30:00',
        proposedEndTime: '2026-09-09T04:30:00',
        disruptionCostScore: 0.0,
        conflictingTrainsCount: 0,
        feasibilityReason: 'Optimal Night Lull Window (01:00 AM - 04:30 AM). Zero passenger and freight disruption.',
        isNightLullWindow: true,
      },
    ],
    shadowBlockOpportunities: [
      {
        assetId: 6,
        assetName: 'Multi-Aspect Color Light Home Signal S-14 (Sahibabad Entry)',
        healthScore: 56,
        recommendationReason: '[SIGNAL_TELECOM] Health condition is 56% (< 70%). Bundling into an Integrated Mega-Block saves ~2.5 hrs of separate line closure.',
      },
      {
        assetId: 8,
        assetName: 'Point Machine PM-102 (Ghaziabad Central Crossover Motor)',
        healthScore: 59,
        recommendationReason: '[SIGNAL_TELECOM] Health condition is 59% (< 70%). Bundling into an Integrated Mega-Block saves ~2.5 hrs of separate line closure.',
      },
    ],
  },
  {
    id: 3,
    title: '25kV Catenary Wire Height Re-tensioning & Dropper Fix',
    trackId: 2,
    trackSectionCode: 'SEC-GZB-NDLS-LINE2',
    startStation: 'GZB',
    endStation: 'NDLS',
    department: 'ELECTRICAL',
    assetId: 13,
    assetName: '25kV AC Catenary Contact Wire (SBB - GZB Line 2 KM 12-16)',
    scheduledDate: '2026-09-08',
    requestedStartTime: '2026-09-08T16:00:00',
    requestedEndTime: '2026-09-08T18:30:00',
    allocatedStartTime: null,
    allocatedEndTime: null,
    purpose: 'OHE thermal expansion adjustment',
    status: 'CONFLICT',
    priority: 'MEDIUM',
    hasConflict: true,
    conflictRemarks: 'Clashes with Shatabdi 12015; Overlaps with Civil & S&T',
    conflicts: [
      {
        trainNumber: '12015',
        trainName: 'New Delhi - Daurai (Ajmer) Shatabdi Express',
        trainType: 'SHATABDI',
        overlapDurationMinutes: 35,
        severity: 'CRITICAL',
      },
    ],
    recommendedSlots: [
      {
        proposedStartTime: '2026-09-09T01:30:00',
        proposedEndTime: '2026-09-09T04:00:00',
        disruptionCostScore: 0.0,
        conflictingTrainsCount: 0,
        feasibilityReason: 'Optimal Night Lull Window (01:00 AM - 04:30 AM). Zero passenger disruption.',
        isNightLullWindow: true,
      },
    ],
  },
  {
    id: 7,
    title: 'Substation Feeder Breaker CB-09 Diagnostic Test',
    trackId: 1,
    trackSectionCode: 'SEC-NDLS-GZB-LINE1',
    startStation: 'NDLS',
    endStation: 'GZB',
    department: 'ELECTRICAL',
    assetId: 14,
    assetName: '25kV AC Traction Substation Feeder Circuit Breaker CB-09',
    scheduledDate: '2026-09-08',
    requestedStartTime: '2026-09-08T05:45:00',
    requestedEndTime: '2026-09-08T07:15:00',
    allocatedStartTime: null,
    allocatedEndTime: null,
    purpose: 'Preventive breaker cycle testing',
    status: 'CONFLICT',
    priority: 'HIGH',
    hasConflict: true,
    conflictRemarks: 'Clashes with Vande Bharat 22436 and Shatabdi 12004',
    conflicts: [
      {
        trainNumber: '22436',
        trainName: 'Vande Bharat Express (New Delhi - Varanasi)',
        trainType: 'VANDE_BHARAT',
        overlapDurationMinutes: 35,
        severity: 'CRITICAL',
      },
      {
        trainNumber: '12004',
        trainName: 'Lucknow Swarna Shatabdi Express',
        trainType: 'SHATABDI',
        overlapDurationMinutes: 35,
        severity: 'CRITICAL',
      },
    ],
  },
  {
    id: 11,
    title: 'Hindon River Bridge Girder Anti-Corrosion Spray',
    trackId: 1,
    trackSectionCode: 'SEC-NDLS-GZB-LINE1',
    startStation: 'NDLS',
    endStation: 'GZB',
    department: 'ENGINEERING',
    assetId: 1,
    assetName: 'Historic Yamuna Bridge BR-01 Steel Girder',
    scheduledDate: '2026-09-08',
    requestedStartTime: '2026-09-08T01:30:00',
    requestedEndTime: '2026-09-08T04:30:00',
    allocatedStartTime: '2026-09-08T01:30:00',
    allocatedEndTime: '2026-09-08T04:30:00',
    purpose: 'Night lull scheduled painting',
    status: 'APPROVED',
    priority: 'LOW',
    hasConflict: false,
    conflictRemarks: 'Approved & locked for maintenance.',
    conflicts: [],
  },
];
